Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 10
      MemorySize: 1152
      Handler: helloworld.App
      CodeUri: D:\aws-lambda-project\HelloWorldFunction
      Runtime: java11
      Architectures:
        - x86_64